export http_proxy="{{ proxy }}"
export https_proxy="{{ proxy }}"
export ftp_proxy="{{ proxy }}"
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
export HTTP_PROXY="{{ proxy }}"
export HTTPS_PROXY="{{ proxy }}"
export FTP_PROXY="{{ proxy }}"
export NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"
