---
#- name: create user
#  become: yes
# user: name={{ system.user }} password={{ system.user |password_hash('sha512') }} append=yes groups=sudo state=present
- name: set proxy settings
  template: src=environment.tpl dest=/etc/environment force=yes
  become: yes
  when: set_proxy

- name: set proxy settings for apt
  template: src=95proxy.tpl dest=/etc/apt/apt.conf.d/95proxy force=yes
  become: yes
  when: set_proxy

- name: check if recommend rules is set for apt
  stat: path=/etc/apt/apt.conf.d/01norecommend
  register: apt_recommend_rules

- name: set recommend rules for apt
  copy:
    content: "APT::Install-Recommends \"0\";\nAPT::Install-Suggests \"0\";\n"
    dest: "/etc/apt/apt.conf.d/01norecommend"
  become: yes
  when: apt_recommend_rules.stat.exists == False

- name: install system packages
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - build-essential

- name: update packages
  become: yes
  apt: upgrade=dist update_cache=yes
  when: keep_updated
