---
- name: Install Git Packages
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - git

- name: Change git config .files
  become: yes
  become_user: "{{ system.user }}"
  template: src={{ item }}.tpl dest=~/{{ item }} force=yes
  with_items:
    - .gitconfig
    - .gitalias
    - .gitignore
