---
- name: Install atom for Debian
  become: yes
  apt: deb=https://atom.io/download/deb

- name: install atom packages
  command: apm install {{ item }}
  with_items:
    - language-ansible
    - language-groovy
