---
- hosts: localhost
  vars_files:
    - vars/all.yml
    - vars/user.yml
    - vars/proxy.yml
  vars:
    system:
      user: bpaulin
  roles:
   - system
   - git
   - terminal
   - xml
   - php
   - nodejs
   - ruby
   - { role: desktop, when: with_gui == True }
   - { role: atom, when: with_gui == True }
   - { role: chrome, when: with_gui == True }
   - { role: terminator, when: with_gui == True }
