---
- name: Install Terminal Packages
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - zsh
    - dtrx
    - ncdu
    - htop
    - elinks
    - bc
    - fortune

- name: Clone oh-my-zsh repo
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh

- name: Change user shell to zsh
  user: name={{ system.user }} shell=/bin/zsh
  become: yes

- name: Install zsh-syntax-highlighting
  git: repo=https://github.com/zsh-users/zsh-syntax-highlighting.git dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Change .zshrc
  template: src=.zshrc.tpl dest=~/.zshrc force=yes

- name: Install vim
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - vim

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Change .vimrc
  template: src=.vimrc.tpl dest=~/.vimrc force=yes

- name: install vim bundles
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  ignore_errors: yes

- name: Install screen, tmux and byobu
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - tmux
    - screen
    - byobu

- name: Change .tmux.conf
  template: src=.tmux.conf.tpl dest=~/.tmux.conf force=yes
